// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package nfsqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/pgvector/pgvector-go"
)

type News struct {
	ID               uuid.UUID
	SourceID         uuid.UUID
	Title            string
	Content          string
	PublishedAt      time.Time
	IngestedAt       time.Time
	ContentHash      string
	Analysis         []byte
	ContentEmbedding pgvector.Vector
	CreatedAt        time.Time
}

type Source struct {
	ID          uuid.UUID
	Name        string
	Credibility float32
	Active      bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
