// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package nfsqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/pgvector/pgvector-go"
)

const addNews = `-- name: AddNews :one
INSERT INTO news (
    id,
    source_id,
    title,
    content,
    published_at,
    ingested_at,
    content_hash,
    analysis,
    content_embedding
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
    ON CONFLICT (content_hash) DO NOTHING
RETURNING id
`

type AddNewsParams struct {
	ID               uuid.UUID
	SourceID         uuid.UUID
	Title            string
	Content          string
	PublishedAt      time.Time
	IngestedAt       time.Time
	ContentHash      string
	Analysis         []byte
	ContentEmbedding pgvector.Vector
}

func (q *Queries) AddNews(ctx context.Context, arg AddNewsParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, addNews,
		arg.ID,
		arg.SourceID,
		arg.Title,
		arg.Content,
		arg.PublishedAt,
		arg.IngestedAt,
		arg.ContentHash,
		arg.Analysis,
		arg.ContentEmbedding,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getSourceByID = `-- name: GetSourceByID :one
SELECT id, name, credibility, active, created_at, updated_at
    FROM sources
    WHERE id = $1
LIMIT 1
`

func (q *Queries) GetSourceByID(ctx context.Context, id uuid.UUID) (Source, error) {
	row := q.db.QueryRow(ctx, getSourceByID, id)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Credibility,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lookupByHash = `-- name: LookupByHash :one
SELECT 1
    FROM news
    WHERE content_hash = $1
LIMIT 1
`

func (q *Queries) LookupByHash(ctx context.Context, contentHash string) (int32, error) {
	row := q.db.QueryRow(ctx, lookupByHash, contentHash)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const lookupEmbedding = `-- name: LookupEmbedding :one
SELECT EXISTS (
    SELECT 1 FROM news
    WHERE content_embedding <=> $1 < 0.15
    AND published_at > now() - interval '24 hours'
    LIMIT 1
)
`

func (q *Queries) LookupEmbedding(ctx context.Context, contentEmbedding pgvector.Vector) (bool, error) {
	row := q.db.QueryRow(ctx, lookupEmbedding, contentEmbedding)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
