// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package nfsqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/pgvector/pgvector-go"
)

const addNews = `-- name: AddNews :one
INSERT INTO news (
    id,
    source_id,
    title,
    content,
    published_at,
    ingested_at,
    content_hash,
    analysis,
    content_embedding
)
SELECT id, source_id, title, content, published_at, ingested_at, content_hash, analysis, content_embedding
FROM json_populate_record(NULL::news, $1::jsonb)
    ON CONFLICT (content_hash) DO NOTHING
RETURNING id
`

func (q *Queries) AddNews(ctx context.Context, dollar_1 []byte) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, addNews, dollar_1)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getSources = `-- name: GetSources :many
SELECT id, name, credibility, active, created_at, updated_at FROM sources
`

// TODO: Пример, взят из гайда, сделать под себя. https://docs.sqlc.dev/en/stable/tutorials/getting-started-postgresql.html
func (q *Queries) GetSources(ctx context.Context) ([]Source, error) {
	rows, err := q.db.Query(ctx, getSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Source
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Credibility,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupByHash = `-- name: LookupByHash :one
SELECT 1
FROM news
WHERE content_hash = $1
LIMIT 1
`

func (q *Queries) LookupByHash(ctx context.Context, contentHash string) (int32, error) {
	row := q.db.QueryRow(ctx, lookupByHash, contentHash)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const lookupEmbedding = `-- name: LookupEmbedding :one
SELECT EXISTS (
    SELECT 1 FROM news
    WHERE content_embedding <=> $1 < 0.12
    AND published_at > now() - interval '24 hours'
    LIMIT 1
)
`

func (q *Queries) LookupEmbedding(ctx context.Context, contentEmbedding pgvector.Vector) (bool, error) {
	row := q.db.QueryRow(ctx, lookupEmbedding, contentEmbedding)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
