// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package nfappsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type News struct {
	ID               pgtype.UUID
	SourceID         pgtype.UUID
	Title            pgtype.Text
	Content          string
	PublishedAt      pgtype.Timestamptz
	IngestedAt       pgtype.Timestamptz
	ContentHash      string
	Analysis         []byte
	ContentEmbedding pgvector.Vector
	CreatedAt        pgtype.Timestamptz
}

type Source struct {
	ID          pgtype.UUID
	Name        string
	Credibility float32
	Active      bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
