// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package nfappsqlc

import (
	"context"
)

const getSources = `-- name: GetSources :many
SELECT id, name, credibility, active, created_at, updated_at FROM sources
`

// TODO: Пример, взят из гайда, сделать под себя. https://docs.sqlc.dev/en/stable/tutorials/getting-started-postgresql.html
func (q *Queries) GetSources(ctx context.Context) ([]Source, error) {
	rows, err := q.db.Query(ctx, getSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Source
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Credibility,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
